name: Windows x64 Release

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.304


      - name: Restore
        run: dotnet restore ZdaszToApp\ZdaszToApp.Desktop\ZdaszToApp.Desktop.csproj

      - name: Build
        run: dotnet publish -c Release -f net9.0 ZdaszToApp\ZdaszToApp.Desktop\ZdaszToApp.Desktop.csproj

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: win-x64-release
          path: ZdaszToApp\ZdaszToApp.Desktop\bin\Debug\net9.0\publish
